name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:  # Allows manual triggers

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          TOTAL_COMMITS=$(gh api graphql -f query='
            query {
              viewer {
                contributionsCollection {
                  totalCommitContributions
                }
              }
            }
          ' --jq '.data.viewer.contributionsCollection.totalCommitContributions')
          echo "TOTAL_COMMITS=$TOTAL_COMMITS" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i 's/Total%20Commits-[0-9]*/Total%20Commits-'"$TOTAL_COMMITS"'/' README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats" && git push)